cart/models.py

check usage of coupon in cart is the problem,
we change the list of validator for invoice

coupon  list of validator in invoice change

---

nakhll_market/models.py

add shop Available and  Publish status

most sold product

---

cart/api.py
cart/models.py
invoice/models.py

reset cart detail( address, coupon, logistic)

reset cart detail

---

nakhll_market/filters.py

We don't have IsActive field in shop model.

remove is active

---

nakhll_market/serializers.py

The image of the shops can be null.

shop profile image can be null

---

nakhll_market/serializers.py

shop State, BigCity, City have changed to Foriegn key
So their serializers must be modified.

fix bug: shop serializers reference state, big_city, city as field not relation

---

nakhll_market/models.py

We checked this method in the meta class.

we dont need to this function any more

---

restapi/views.py

so it will return validationerror if bigcity is not numeric

BigCity id must be number

---

nakhll_market/serializers.py

update is not compatible with new state, big_city, city serializers

ShopAllSettingsSerializer update method

---

logistic/interfaces.py
shop/admin.py

- reformat code.
- change shop feature invoice admin class

150 تغییر هزینه های لاجستیک توسط ادمین پنل

---

restapi/validators.py
restapi/views.py

create a decorator for the validation of get params
and use it in BigCityList and CityList
Sorry this has some code style modifications but
in restapi.views[186, 196] are  added and the validators file

validate get params data are numeric

---

nakhll_market/api.py
nakhll_market/serializers.py

You didn't fix create shop serializer.
I fixed it

create shop fix

---

accounting/views.py

types must match

---

nakhll_auth/api.py

so I add CompleteAuthSerializer to CompleteAuthViewSet

we need serializer_class for auth in browser

---

invoice/templates/admin/custom/invoice_changeform.html
nakhll/settings.py

templates seem useless. so I deprecate them. templates are not deleted

deprecate templates

---

accounting/urls.py
accounting/views.py
nakhll/settings.py
nakhll/urls.py
nakhll/utils.py
nakhll_market/admin.py
nakhll_market/api.py
nakhll_market/api_urls.py
nakhll_market/models.py
nakhll_market/resources.py
nakhll_market/serializers.py
requirements.txt
shop/api.py
shop/resources.py

replace django-excel-response with django-import-export
rename Shop property of totla_products to products_count
add excel export to ProfileAdmin
tune profile admin panel query performance
modify profile admin panel fields
add profile admin panel filter of ProfileHasShopFilter

django-import-export

---

nakhll_market/resources.py

specify fields to defer useless fields

specify profile admin export fields

---

invoice/managers.py
invoice/models.py
nakhll/utils.py
nakhll_market/admin.py
nakhll_market/models.py
nakhll_market/resources.py

some fields in ShopAdminResource exported that have report functionality
report fields are declared as model properties
we have serious performance issues

enhance admin panel for shops

---

nakhll_market/admin.py

icontains lookup can't be done on relational fields so I change `FK_ShopManager` to `FK_ShopManager__username`

bug fix: search_fields can't be done on relation field

---

nakhll_market/api.py
nakhll_market/serializers.py

bug fix: as products property is defined for shop
so we can't annotate with the same name

bug fix: server side sitemap endpoint

---

cart/api.py
coupon/validators.py

set status_code based on the serializer is valid

bug fix: self.budget is not exists
